name: multiple runners and choose jobs

on:
  workflow_dispatch:
    inputs:
      runner:
        description: "Select the runner"
        required: true
        type: choice
        options:
          - ubuntu-latest
          - ubuntu-22.04
          - self-hosted
          - windows-latest

      jobs_name:
        description: "Enter jobs to run (comma separated: buildjob,testjob,deployjob)"
        required: true
        type: string

jobs:
  buildjob:
    if: contains(github.event.inputs.jobs_name, 'buildjob')
    runs-on: ${{ github.event.inputs.runner }}
    steps:
      - name: Build code
        run: echo "Building the code"

  testjob:
    if: contains(github.event.inputs.jobs_name, 'testjob')
    runs-on: ${{ github.event.inputs.runner }}
    steps:
      - name: Test code
        run: echo "Testing the code on runner"

  deployjob:
    if: contains(github.event.inputs.jobs_name, 'deployjob')
    runs-on: ${{ github.event.inputs.runner }}
    steps:
      - name: Deploy code
        run: echo "Deploying the code"
