name: Build python application
on: 
  workflow_dispatch: 
  push:
    paths:
      - Jenkins-Python-Pipeline-demo/**
jobs:
  job1:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Jenkins-Python-Pipeline-demo
    steps:
      - name: clone the repo
        uses: actions/checkout@v6
        
      - name: Install python on runner
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
          
      - name: Install Python Dependencies
        run | 
        pip install --upgrade pip
        pip install -r requirements.txt
        
      - name: set pythonPATH
        run: echo "PYTHONPATH"=$GITHUB_WORKSPACE >> $GITHUB_ENV
        
      - name: Run tests
        run: pytest tests --cov=app --cov-report=xml
